fitnessApp/urls.py
from os import stat
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitnessadmin.urls')),
    path('users/', include('users.urls')),
    path('instructormodule/', include('fitnessInstructor.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profiles, name="profiles"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),
    path('courses/', views.courses, name="courses"),
    path('instructors/', views.instructors, name="instructors"),
    path('course/<str:pk>', views.course, name="course"),
    path('instructor/<str:pk>', views.instructor, name="instructor"),
    path('enroll/', views.enroll, name="enroll"),
    path('chartEnrollment', views.bar_chart_enrollment_json,
         name='bar_chart_enrollment_json'),
]

fitnessadmin/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

from users.models import Student

# class Student(models.Model):
#     studentid = models.AutoField(db_column='studentId', primary_key=True)  # Field name made lowercase.
#     studentfirstname = models.CharField(db_column='studentFirstName', max_length=45)  # Field name made lowercase.
#     studentphonenumber = models.CharField(db_column='studentPhoneNumber', max_length=45)  # Field name made lowercase.
#     studentlastname = models.CharField(db_column='studentLastName', max_length=45, blank=True, null=True)  # Field name made lowercase.
#     studentemailid = models.EmailField(db_column='studentEmailId', max_length=45)  # Field name made lowercase.
#     studentpassword = models.CharField(db_column='studentPassword', max_length=45)  # Field name made lowercase.

#     class Meta:
#         managed = False
#         db_table = 'student'
    
#     def __str__(self):
#         return str(self.studentid)

class Instructor(models.Model):
    instructorid = models.AutoField(db_column='instructorId', primary_key=True)  # Field name made lowercase.
    instructorname = models.CharField(db_column='instructorName', max_length=45)  # Field name made lowercase.
    instructorcourse = models.CharField(db_column='instructorCourse', max_length=45, blank=True, null=True)  # Field name made lowercase.
    instructorskills = models.CharField(db_column='instructorSkills', max_length=45, blank=True, null=True)  # Field name made lowercase.
    instructorphonenumber = models.CharField(db_column='instructorPhoneNumber', max_length=45)  # Field name made lowercase.
    instructoremail = models.CharField(db_column='instructorEmail', max_length=45)  # Field name made lowercase.
    instructorpassword = models.CharField(db_column='password', max_length=45)  # Field name made lowercase.
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    created = models.DateTimeField(auto_now_add=True)


    class Meta:
        managed = False
        db_table = 'instructor'
    
    def __str__(self):
        return self.instructorname

class Course(models.Model):
    courseid = models.AutoField(db_column='courseId', primary_key=True)  # Field name made lowercase.
    coursename = models.CharField(db_column='courseName', max_length=45)  # Field name made lowercase.
    coursedescription = models.CharField(db_column='courseDescription', max_length=100, blank=True, null=True)  # Field name made lowercase.
    trainer = models.ForeignKey('Instructor', models.DO_NOTHING, db_column='trainer', blank=True, null=True)
    featured_image = models.ImageField(
        null=True, blank=True, default="default.jpg")
    zoom_link = models.CharField(max_length=2000, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'course'
    
    def __str__(self):
        return self.coursename
class Enroll(models.Model):
    studentid = models.ForeignKey(Student, models.DO_NOTHING, db_column='studentId')  # Field name made lowercase.
    courseid = models.ForeignKey(Course, models.DO_NOTHING, db_column='courseId')  # Field name made lowercase.
    enrollid = models.AutoField(db_column='enrollId', primary_key=True)  # Field name made lowercase.
    
    class Meta:
        managed = False
        db_table = 'enroll'

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.

class Student(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(
        null=True, blank=True, upload_to='profiles/', default="profiles/user-default.png")
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        # labels = {
        #     'first_name': 'Name',
        # }

users/views.py
from django.contrib.auth.models import User
from django.contrib import messages
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from .utils import searchCourses, searchInstructors
from django.views.generic import TemplateView
from chartjs.views.lines import BaseLineChartView
from .forms import CustomUserCreationForm
import mysql.connector
from fitnessadmin.models import Course, Instructor, Enroll
from .models import Student
# Create your views here.
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="admin123",
    database="fitnessdb"
)
mycursor = mydb.cursor()

mycursor.execute(
    """SELECT count(*),c.courseName FROM enroll e, course c where e.courseid=c.courseId  group by e.courseid""")

myresult = mycursor.fetchall()
print(myresult)

mycursor.execute(
    """SELECT count(*),i.instructorName FROM instructor i, course c where c.trainer = i.instructorid group by i.instructorId;""")
myresultIns = mycursor.fetchall()
print(myresultIns)


def bar_chart_enrollment_json(request):

    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        password="admin123",
        database="fitnessdb"
    )
    mycursor = mydb.cursor()

    mycursor.execute(
        """SELECT count(*),c.courseName FROM enroll e, course c where e.courseid=c.courseId  group by e.courseid""")

    myresult = mycursor.fetchall()
    print(myresult)
    mycursor.execute(
        """SELECT count(*),i.instructorName FROM instructor i, course c where c.trainer = i.instructorid group by i.instructorId;""")
    myresultIns = mycursor.fetchall()
    print(myresultIns)
    labels = [value[1] for value in myresult]
    data = [value[0] for value in myresult]

    labels1 = [value[1] for value in myresultIns]
    data1 = [value[0] for value in myresultIns]
    return JsonResponse(data={
        'labels': labels,
        'data': data,
        'labels1': labels1,
        'data1': data1,
    })


def profiles(request):

    return render(request, 'dashboard.html')


def loginUser(request):
    page = 'login'
    context = {"page": page}

    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')
            return render(request, 'users/login_register.html')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('profiles')
            # return redirect(request.GET['next'] if 'next' in request.GET else 'account')

        else:
            messages.error(request, 'Username OR password is incorrect')

    return render(request, 'users/login_register.html', context)
    # return HttpResponse("<h1>ogin required</h1>")


def logoutUser(request):
    logout(request)
    return redirect('login')


def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            try:
                print("USERname!!!!!!!", user.first_name)
                student = Student.objects.create(
                    user=user, name=user.first_name, email=user.email, username=user.username)
                student.save()
                messages.success(request, 'User account was created!')
                login(request, user)
            except:
                messages.error(request, 'User account was not created!')

            return redirect('profiles')

        else:
            messages.error(
                request, 'An error has occurred during registration')

    context = {'page': page, 'form': form}
    return render(request, 'users/login_register.html', context)


@login_required(login_url='login')
def courses(request):

    if request.method == "POST":
        print(request.user.username)
        print(request.POST.get('data-course'))
        print(request.POST)
        # student = Student.objects.filter(Q(studentfirstname="Student1"))

        # course1 = Course.objects.filter(coursename="Yoga")
        # print(student[0].studentid)
        # print(course1)
        # enroll = Enroll.objects.create(studentid=student[0],courseid=course1[0])
        # enroll.save()
    courses, search_query = searchCourses(request)
    context = {'courses': courses, 'search_query': search_query}
    return render(request, "users/courses.html", context)


@login_required(login_url='login')
def course(request, pk):
    enrolledFlag = False
    existingFlag = True

    courseObj = Course.objects.filter(courseid=pk)
    studentObj = Student.objects.filter(username=request.user.username)
    enrollData = Enroll.objects.filter(Q(studentid=studentObj[0]) &
                                       Q(courseid=courseObj[0]))
    print(enrollData)

    if enrollData:
        enrolledFlag = True
        messages.success(
            request, "Already enrolled to {}".format(courseObj[0]))
    if request.method == "POST":
        print(pk)
        print(request.user.username)
        if request.POST["enroll"] == "Unsubscribe":
            enrollData.delete()
            messages.success(
                request, "Unsubscribed from {}".format(courseObj[0]))
            return redirect('courses')

        elif not enrollData:
            enroll = Enroll.objects.create(
                studentid=studentObj[0], courseid=courseObj[0])
            enroll.save()
            messages.success(
                request, "Successfully enrolled to {}".format(courseObj[0]))
            enrolledFlag = True

    course = Course.objects.get(courseid=pk)
    context = {'course': course, 'enrolledFlag': enrolledFlag}
    return render(request, 'users/single-course.html', context)


@login_required(login_url='login')
def instructors(request):
    instructors, search_query = searchInstructors(request)
    context = {'instructors': instructors, 'search_query': search_query}
    return render(request, "users/instructors.html", context)


@login_required(login_url='login')
def instructor(request, pk):
    instructor = Instructor.objects.get(instructorid=pk)
    context = {'instructor': instructor}
    return render(request, 'users/instructor-profile.html', context)


@login_required(login_url='login')
def enroll(request):
    print("Requested user", request.user.username)
    courseList = []
    courseidList = []
    context = {'courses': courseList}
    try:
        allStudents = Student.objects.all()
        print(allStudents)
        studentObj = Student.objects.filter(username=request.user.username)
        print("Student object:", studentObj)
        print("Student object ID:", type(studentObj[0].id))

        enroll = Enroll.objects.filter(studentid=studentObj[0].id)
        print("Enroll details: ", enroll)
        for e in enroll:
            print(e.courseid.courseid)
            if e.courseid.courseid not in courseidList:
                courseidList.append(e.courseid.courseid)
                courseList.append(e.courseid)
            print(courseList)
        context = {'courses': courseList}
        return render(request, 'users/enroll.html', context)
    except Exception as e:
        return render(request, 'users/enroll.html', context)

users/templates/users/courses.html
{% extends 'main.html' %}

{% block content %}


<!-- Main Section -->
<main class="projects">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>Search for <span>Courses</span></h2>
            </div>

            <div class="hero-section__search">
                <form id='searchForm' class="form" action="{% url 'courses' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search By Courses </label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            placeholder="Search by Courses" value="{{search_query}}" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
        </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="projectsList">
        <div class="container">
            <div class="grid grid--three">
                {% for course in courses %}
                <div class="column">
                    <div class="card project">
                        <a href="{% url 'course' course.courseid %}" class="project">
                            <img class="project__thumbnail" src="{{course.featured_image.url}}" alt="project thumbnail" />
                            <div class="card__body">
                                <h3 class="project__title">{{course.coursename}}</h3>
                                <p><a class="project__author" href="{% url 'instructor' course.trainer.instructorid %}">By
                                        {{course.trainer.instructorname}}</a>
                                </p>
                                <div class="project__tags">
                                    <span class="tag tag--pill tag--main">
                                        <small>{{course.trainer.instructorskills}}</small>
                                    </span>
                                </div>
                                <form action="{% url 'course' course.courseid %}" method="POST">
                                {% csrf_token %}
                                <input id="enrollForm" class="btn btn--sub btn--lg  my-md" type="submit" value="Enroll" name='enroll' data-course="{{ course.coursename}}"/>
                                </form>
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>

    {% comment %} {% include 'pagination.html' with queryset=projects custom_range=custom_range %} {% endcomment %}

</main>

<script>
data = document.getElementsByClassName("btn btn--sub btn--lg  my-md")

console.log("class data: ", data)

for (let i=0; data.length > i; i++ ) {
    data[i].addEventListener('click', (e) => {
        console.log('Clicked Enroll:', i)
        console.log("Course name:", e.target.dataset.course)
    })
}

function myFunction() {
  alert("The form was submitted");
  console.log("In courses script");
}
</script>
{% endblock content %}

users/templates/users/enroll.html
{% extends 'main.html' %}

{% block content %}


<main class="projects">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>Search for <span>Enrolled Courses</span></h2>
            </div>
            <div class="hero-section__search">
                <form id='searchForm' class="form" action="{% url 'courses' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search By Enroll </label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            placeholder="Search by Courses" value="{{search_query}}" />
                    </div>
                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
        </div>
    </section>
    <section class="projectsList">
        <div class="container">
            <div class="grid grid--three">
                {% if not courses%}
                    <h3 class="project__title">Not enrolled to any courses yet, </h3>
                    <p><a href={% url 'courses'%}>click here to list available courses</a></p
                {% endif %}
                {% for course in courses %}
                <div class="column">
                    <div class="card project">
                        <a href="{% url 'course' course.courseid %}" class="project">
                            <img class="project__thumbnail" src="{{course.featured_image.url}}" alt="project thumbnail" />
                            <div class="card__body">
                                <h3 class="project__title">{{course.coursename}}</h3>
                                <p><a class="project__author" href="{% url 'instructor' course.trainer.instructorid %}">By
                                        {{course.trainer.instructorname}}</a>
                                </p>
                                <div class="project__tags">
                                    <span class="tag tag--pill tag--main">
                                        <small>{{course.trainer.instructorskills}}</small>
                                    </span>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
</main>

{% endblock content %}

users/templates/users/instructor-profile.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <img class="avatar avatar--xl" src="{{ instructor.featured_image.url }}" />
                        <h2 class="dev__name">{{instructor.instructorname}}</h2>
                        <p class="dev__title">{{instructor.instructorcourse}}</p>
                        <p class="dev__title">{{instructor.instructorphonenumber}}</p>
                        <p class="dev__title">{{instructor.instructoremail}}</p>
                        
                    </div>
                </div>
            </div>
            
                <div class="devInfo">
                    <h3 class="devInfo__title">Courses</h3>
                    <div class="grid grid--two">
                        {% for course in instructor.course_set.all %}
                        <div class="column">
                            <div class="card project">
                                <a href="{% url 'course' course.courseid %}" class="project">
                                    <img class="project__thumbnail" src="{{course.featured_image.url}}"
                                        alt="project thumbnail" />
                                    <div class="card__body">
                                        <h3 class="project__title">{{course.coursename}}</h3>
                                        <p><a class="project__author"
                                                href="{% url 'instructor' course.trainer.instructorid %}">By
                                                {{course.trainer.instructorname}}</a>
                                        </p>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

users/templates/users/instructors.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>CONNECT WITH <span>Instructors</span></h2>
            </div>

            <div class="hero-section__search">

                <form id="searchForm" class="form" action="{% url 'instructors' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search Instructors </label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            value="{{search_query}}" placeholder="Search by instructors" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>

            </div>
        </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
        <div class="container">
            <div class="grid grid--three">

                {% for instructor in instructors %}
                <div class="column card">
                    <div class="dev">
                        {% comment %} <a href="{% url 'instructors' %}" class="card__body"> {% endcomment %}
                            <div class="dev__profile">
                                <img class="avatar avatar--md" src="{{ instructor.featured_image.url }}" alt="image" />
                                <div class="dev__meta">
                                    <h3><a href="{% url 'instructor' instructor.instructorid %}">{{instructor.instructorname}}</a></h3>
                                    <h5>{{instructor.instructorskills}}</h5>
                                </div>
                            </div>
                            <p class="dev__info">{{instructor.instructorcourse}}</p>
                            <div class="dev__skills">

                                {% comment %} {% for skill in profile.skill_set.all|slice:"5" %}
                                <span class="tag tag--pill tag--main">
                                    <small>{{skill}}</small>
                                </span>
                                {% endfor %} {% endcomment %}

                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>

    {% comment %} {% include 'pagination.html' with queryset=profiles custom_range=custom_range %} {% endcomment %}
</main>

{% endblock content %}

users/templates/users/login_register.html
{% extends 'main.html' %}
{% load static %}
{% block content %}


{% if page == 'register' %}

<div class="auth">
    <div class="card">
        <div class="auth__header text-center">
            <a href="/">
                <img src="{% static 'images/icon.svg' %}" alt="icon" />
            </a>
            <h3>Register an Account</h3>
            <p>Create an account</p>
        </div>

        <form method="POST" action="{% url 'register' %}" class="form auth__form">
            {% csrf_token %}

            {% for field in form %}
            <div class="form__field">
                <label for="formInput#text">{{field.label}}</label>
                {{field}}

                <!-- {% if field.help_text %}
                <small>{{field.help_text}}</small>
                {% endif %} -->

                {% for error in field.errors %}
                <p style="color: red;">{{error}}</p>
                {% endfor %}

            </div>

            {% endfor %}

            <div class="auth__actions">
                <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
            </div>
        </form>
        <div class="auth__alternative">
            <p>Already have an Account?</p>
            <a href="{% url 'login' %}">Log In</a>
        </div>
    </div>
</div>



{% else %}

<div class="auth">

    <div class="card">

        <div class="auth__header text-center">
            <a href="/">
                <img src="{% static 'images/icon.svg' %}" alt="icon" />
            </a>
            <h3>Account Login</h3>
            <p>Hello Trainee, Welcome Back!</p>
        </div>

        <form action="" method="POST" class="form auth__form">
            {% csrf_token %}
            <!-- Input:Username -->
            <div class="form__field">
                <label for="formInput#text">Username: </label>
                <input class="input input--text" id="formInput#text" type="text" name="username"
                    placeholder="Enter your username..." />
            </div>

            <!-- Input:Password -->
            <div class="form__field">
                <label for="formInput#password">Password: </label>
                <input class="input input--password" id="formInput#passowrd" type="password" name="password"
                    placeholder="••••••••" />
            </div>

            <div class="auth__actions">
                <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
            </div>

        </form>

        <div class="auth__alternative">
            <p>Don’t have an Account?</p>
            <a href="{% url 'register' %}">Sign Up</a>
        </div>
    </div>
</div>


{% endif %}




{% endblock content %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

<main class="projects">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>Welcome to <span>Fitness</span> World</h2>
            </div>
        </div>
    </section>
</main>

{% endblock content%}

users/templates/users/single-course.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="singleProject my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <h3 class="singleProject__subtitle">Tools & Stacks</h3>
                <div class="singleProject__toolStack">
                    {% for tag in course.trainer.all %}
                    <span class="tag tag--pill tag--sub tag--lg">
                        <small>{{tag}}</small>
                    </span>
                    {% endfor %}

                </div>

                {% if not enrolledFlag %}
                <form action="" method="POST">
                {% csrf_token %}
                <input id="enrollForm" class="btn btn--sub btn--lg  my-md" type="submit" value="Enroll" name='enroll' />
                </form>
                {% elif enrolledFlag and course.zoom_link %}
                <form action="" method="POST">
                {% csrf_token %}
                <a class="singleProject__liveLink" href="{{course.zoom_link}}" target="_blank"><i
                        class="im im-external-link"></i>Click here to join the Zoom session
                </a>
                <input id="unenrollForm" class="btn btn--sub btn--lg  my-md" type="submit" value="Unsubscribe" name='enroll' />
                </form>
                {% endif %}
                
            </div>
            <div class="column column--2of3">
                <img class="singleProject__preview" src="{{ course.featured_image.url }}" alt="portfolio thumbnail" />
                {% comment %} <a href="{% url 'user-profile' project.owner.id  %}"
                    class="singleProject__developer">{{project.owner.name}}</a> {% endcomment %}
                <h2 class="singleProject__title">{{course.coursename}}</h2>
                <h3 class="singleProject__subtitle">About the Course</h3>
                <div class="">
                    {{course.coursedescription}}
                </div>
                
            </div>
        </div>
    </div>
    </div>
</main>

{% endblock content %}